mybatis:
  type-aliases-package: com.flab.foodeats.domain.user, com.flab.foodeats.application.user,
                        com.flab.foodeats.domain.shop, com.flab.foodeats.application.shop,
                        com.flab.foodeats.domain.menu

  mapper-locations: mapper/xml/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodeats?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true

  redis:
    session:
      host: localhost
      port: 6379


