mybatis:
  type-aliases-package: com.flab.foodeats.domain.user, com.flab.foodeats.application.user
  mapper-locations: mapper/xml/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodeats?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

